# Generated by Django 3.0.6 on 2020-05-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('travellagency', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
