# Generated by Django 3.0.6 on 2020-05-27 16:20

from django.db import migrations, models
import order.validators


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, validators=[order.validators.validate_phone]),
        ),
    ]
